version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspace:cached
    command: sleep infinity
    depends_on:
      - db
      - embeddings_db
    networks:
      - devnet

  db:
    image: neo4j:2025.05-community
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/password123
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - neo4j_data:/data/db
    networks:
      - devnet

  embeddings_db:
    image: chromadb/chroma:latest
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - chroma_data:/data/embeddings_db
    networks:
      - devnet

volumes:
  neo4j_data:
  chroma_data:

networks:
  devnet:
